#!/usr/bin/env node
/* Builds background.js = aggregate.js + background.src.js.
 *
 * Drift runs a single background script and cannot import a second file, so
 * the tested aggregation module is inlined. Usage:
 *   node build.js           write background.js
 *   node build.js --check   exit 1 if background.js is out of date
 */
"use strict";
const fs = require("fs");
const path = require("path");

function build(dir) {
  const read = (name) => fs.readFileSync(path.join(dir, name), "utf8").replace(/\r\n/g, "\n");
  const header =
    "/* GENERATED by build.js from aggregate.js + background.src.js. Do not edit; edit those and run `node build.js`. */\n";
  return header + read("aggregate.js") + "\n" + read("background.src.js");
}

module.exports = { build };

if (require.main === module) {
  const out = path.join(__dirname, "background.js");
  const text = build(__dirname);
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(out) ? fs.readFileSync(out, "utf8").replace(/\r\n/g, "\n") : "";
    if (current !== text) {
      console.error("background.js is out of date: run `node build.js`");
      process.exit(1);
    }
    console.log("background.js is up to date");
  } else {
    fs.writeFileSync(out, text);
    console.log("wrote background.js (" + text.length + " bytes)");
  }
}
